/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAlert: typeof import('./components/TheAlert.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheCurrencySelector: typeof import('./components/TheCurrencySelector.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheTable: typeof import('./components/TheTable.vue')['default']
  }
}
